# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-28 04:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lock_tokens', '0002_locktoken_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='locktoken',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
